/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Data to display inside table
 */
export type Data = string;

/**
 * Component used to display tabular data
 */
export interface InfoTableProps {
  data?: Data;
}
